### ISSUE TITLE
suggestion: mobile left padding

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/plain#47]
you probably have the space the decrease the left-margin on mobile so that the text can expand farther:

![image](https://user-images.githubusercontent.com/2880174/150392500-ca211369-da89-4e70-8f02-540e9006fa22.png)

**Comment by mmcghee18** [comment]
That space on the left is needed so that the standard version can peek out when the plain version is toggled into place. If i make it smaller, there's not enough space for it off to the left, in my opinion
